# Generated by Django 3.2.8 on 2021-11-02 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storefront', '0007_category_is_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='Items quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.product', verbose_name='Order item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PROCESSING', 'Processing'), ('ON_DELIVERY', 'On delivery'), ('CANCELLED', 'Canceled'), ('RETURNED', 'Returned'), ('FINISHED', 'Finished')], max_length=50, verbose_name='Status')),
                ('finished_date', models.DateField(blank=True, null=True, verbose_name='Finished date')),
                ('items', models.ManyToManyField(to='cart.OrderItem', verbose_name='Items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
