# Generated by Django 3.2.8 on 2021-11-02 20:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='KZ', max_length=2, verbose_name='Country'),
        ),
    ]
