# Generated by Django 3.2.8 on 2021-11-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PROCESSING', 'Processing'), ('ON_DELIVERY', 'On delivery'), ('CANCELED', 'Canceled'), ('RETURNED', 'Returned'), ('FINISHED', 'Finished')], max_length=50, verbose_name='Status'),
        ),
    ]
