# Generated by Django 3.2.8 on 2021-10-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Discount price'),
        ),
    ]
