# Generated by Django 3.2.8 on 2021-10-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_alter_category_parent_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecontainer',
            old_name='name',
            new_name='title',
        ),
    ]
