# Generated by Django 3.2.8 on 2021-10-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_alter_stock_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
