# Generated by Django 3.2.8 on 2021-10-31 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_image_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='storefront.stock', verbose_name='Product stock'),
        ),
    ]
