# Generated by Django 3.2.8 on 2021-10-31 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='file',
            field=models.FileField(upload_to='stock', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='Price list'),
        ),
    ]
