# Generated by Django 3.2.8 on 2021-11-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_category_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Product image'),
        ),
    ]
